export const AttendanceData=[
    {
        date:'2024-05-01',
        status:'Absent',
    },
    {
        date:'2024-05-02',
        status:'Absent',
    },
    {
        date:'2024-05-03',
        status:'Holiday',
    },
    {
        date:'2024-05-06',
        status:'Present',
        location:'Home',
        shift:'Day',
    },
    {
        date:'2024-05-07',
        status:'Present',
        location:'Home',
        shift:'Day',
    },
    {
        date:'2024-05-08',
        status:'Present',
        location:'Home',
        shift:'Night',
    },
    {
        date:'2024-05-09',
        status:'Present',
        location:'Home',
        shift:'Day',
    },
    {
        date:'2024-05-10',
        status:'Present',
        location:'Home',
        shift:'Day',
    },
    {
        date:'2024-05-13',
        status:'Present',
        location:'Home',
        shift:'Night',
    }, {
        date:'2024-05-14',
        status:'Absent',
    },
    {
        date:'2024-05-15',
        status:'Absent',
    }, {
        date:'2024-05-16',
        status:'Absent',
    },
    {
        date:'2024-05-17',
        status:'Present',
        location:'Home',
        shift:'Day',
    },
    {
        date:'2024-05-20',
        status:'Present',
        location:'Home',
        shift:'Day',
    },
    {
        date:'2024-05-21',
        status:'Present',
        location:'Home',
        shift:'Night',
    },
    {
        date:'2024-05-22',
        status:'Present',
        location:'Home',
        shift:'Day',
    },
    {
        date:'2024-05-23',
        status:'Present',
        location:'Home',
        shift:'Day',
    },
    {
        date:'2024-05-24',
        status:'Present',
        location:'Office',
        shift:'Night',
    },
    {
        date:'2024-05-27',
        status:'Present',
        location:'Home',
        shift:'Day',
    },
    {
        date:'2024-05-28',
        status:'Present',
        location:'Home',
        shift:'Day',
    },
    {
        date:'2024-05-29',
        status:'Present',
        location:'Home',
        shift:'Day',
    },
    {
            date:'2024-05-30',
            status:'Present',
            location:'Office',
            shift:'Day',
        
    
    },
    {
        date:'2024-05-31',
        status:'Present',
        location:'Home',
        shift:'Day',
    

},
]