export const EmployeeManagementData = [
  {
    id: 1,
    name: "Farhan",
    designation: "Frontend Developer",
    age: 21,
    gender: "Male",
    bloodgroup: "O Positive",
    city: "Vidhyanagar",
    doj: "Feb 19,2024",
    status: "Active",
  },
  {
    id: 2,
    name: "Nitin",
    designation: "Frontend Developer",
    age: 26,
    gender: "Male",
    bloodgroup: "A Positive",
    city: "Goa",
    doj: "Feb 12,2024",
    status: "Active",
  },
  {
    id: 3,
    name: "Priyanshu",
    designation: "Frontend Developer",
    age: 23,
    gender: "Male",
    bloodgroup: "B Positive",
    city: "Jagatpura",
    doj: "Feb 19,2024",
    status: "Past",
  },
  {
    id: 4,
    name: "Lakshya",
    designation: "Salesforce Developer",
    age: 21,
    gender: "Male",
    bloodgroup: "O Positive",
    city: "Chaksu",
    doj: "Feb 12,2024",
    status: "Past",
  },
  {
    id: 5,
    name: "Ishita",
    designation: "HR",
    age: 25,
    gender: "Female",
    bloodgroup: "B Positive",
    city: "Jagatpura",
    doj: "July 19,2022",
    status: "Active",
  },
  {
    id: 6,
    name: "Divyanshi",
    designation: "QA Engineer",
    age: 22,
    gender: "Female",
    bloodgroup: "O Positive",
    city: "Jaipur",
    doj: "Feb 19,2024",
    status: "Active",
  },
  {
    id: 7,
    name: "Akshat",
    designation: "Salesforce Developer",
    age: 24,
    gender: "Male",
    bloodgroup: "O Negative",
    city: "Sitapura",
    doj: "Feb 7,2024",
    status: "Active",
  },
];
